### ISSUE TITLE
Requires an GitHub access token to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by simeon-smith** [phpDocumentor/TypeResolver#100]
When installing on Ubuntu 18.04 this library requires an access token because it is trying to access https://api.github.com/repos/phpDocumentor/TypeResolver/zipball/cf842904952e64e703800d094cdf34e715a8a3ae. 

Please remove this requirement.

**Comment by jaapio** [comment]
Hi,
How did you try to install this lib? I never heard anyone else complaining about the accessibility of the project. And with the number of downloads this project has, I think somebody else would have complained before. 

If you can provide me some more information about what you did I might be able to help you. 

Tnx

**Comment by simeon-smith** [comment]
Hello Jaap,

It is a dependency of Craft CMS. I simple ran a composer install. However, over the next several hours I had some people on the team report a similar issue with other compose dependencies. And I haven’t seen the issue since for other Craft projects. I think it may have been a temporary issue with Github. I’ll keep you posted if I run into it again.

Simeon

**Comment by jaapio** [comment]
I will close this issue for now. Please create a new issue when the issue popup again.
