### ISSUE TITLE
Support more scalar types of psalm

### ISSUE THREAD

**Issue by smoench** [phpDocumentor/TypeResolver#111]
Hey, 
would it be possible to support more [scalar types of psalm](https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/)?
Some are already supported but those aren't:

- array-key
- trait-string
- callable-string
- numeric-string

I got this as a feature request https://github.com/sensiolabs-de/deptrac/issues/329 but I think the best place would be here. So everyone can benefit.

**Comment by jaapio** [comment]
well technically this might be possible... but I'm not sure what we can do with a feature like that... psalm and phpstan do have more context than this library. the `class-string` for example is supported because we have enough context to know what it means. But for the others, I don't know.

I must admit that I never used them, so I don't know what this library should do with those types. 

Can you explain what you expect from this library to happen?

**Comment by smoench** [comment]
Currently they are interpreted as an `Object_`-type. I expect they are resolved as its own type and I think there is no need for more context. This should be done by the tool using this library.

**Comment by jaapio** [comment]
Having them as new types might make sense since the current behavior is invalid anyway, classes like `array-key` cannot be defined. So I think we can at these types. 

I would love to review a PR for this proposed types.

**Comment by mvriel** [comment]
Technically these are Pseudo-types derived from the type String; so new pseudotypes that extend the String type would be nice there

**Comment by orklah** [comment]
> Technically these are Pseudo-types derived from the type String

array-key is kinda different. It may be a string, but it may also be an int

**Comment by mvriel** [comment]
Oh wait, array-key; but that can be any key-type right? Because PHP arrays support more than ints and strings

**Comment by orklah** [comment]
> Oh wait, array-key; but that can be any key-type right? Because PHP arrays support more than ints and strings

Technically, no.
PHP will cast everything into either string or array:
https://3v4l.org/PahFL

array-key is just an alias for int|string in the context of array keys. At least, it's the definition used by Psalm:
https://psalm.dev/r/a0dd544afe
Phpstan:
https://phpstan.org/r/8c98e657-b4f7-43b3-aec1-54dc6af4fd10

And probably Phan, I don't use it enough to be sure

**Comment by mvriel** [comment]
Thanks for clarifying that Orklah. It would mean that the array-key pseudo-type a bit of an odd one is since it is secretly a compound type of int and string. Special care is needed to support that one

**Comment by smoench** [comment]
I added a PR #112 where we could discuss how it could be implemented :-)
