### ISSUE TITLE
Bug in last commit #136

### ISSUE THREAD

**Issue by ilohpro** [phpDocumentor/TypeResolver#150]
Hello,

Since 1.6.0 has been published, we can't anymore run phpunit with phpdocumentor because the next errors is throw for each test : 
`Fatal error: Class phpDocumentor\Reflection\PseudoTypes\List_ may not inherit from final class (phpDocumentor\Reflection\Types\Array_) in /builds/iloh/iloh_api/vendor/bin/.phpunit/phpunit-9.5-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php on line 27`

This commit is I think the problem : https://github.com/phpDocumentor/TypeResolver/pull/136/files

Does anyone else have this error ?
Is already a solution in progress ?

Thank you,
Damien

**Comment by jaapio** [comment]
Please check: https://github.com/phpDocumentor/TypeResolver/issues/148 

You are using symfony + PHPUnit bridge, which causes issues.

**Comment by jaapio** [comment]
As you are the third person in a few days having this problem I contacted the symfony team to see what we can do to improve on this.

**Comment by ilohpro** [comment]
Thank you for your fast answer and sorry for duplicate thread, i haven't seen before that there was closed threads.
Ok for Symfony, yes it would be nice, and i confirm that the simple update of the package throught composer have done the job :)
