### ISSUE TITLE
Integer Range Issue

### ISSUE THREAD

**Issue by voku** [phpDocumentor/TypeResolver#161]
e.g. ```int<0,1>``` isn't working currently 😕

Fix: https://github.com/phpDocumentor/TypeResolver/pull/153

**Comment by jaapio** [comment]
I merged your PR, but we do have a failing test version right now. I need to check why PHPUnit is failing on PHP 7.2. before I can create a new release.

**Comment by villfa** [comment]
The problem came from PHPUnit.
There was a regression in 8.5.24, but it has been fixed in 8.5.25: https://github.com/sebastianbergmann/phpunit/issues/4934

So if you rerun the tests it should be ok now.

**Comment by jaapio** [comment]
Release is created
