### ISSUE TITLE
PHP 7.1 Incompatible

### ISSUE THREAD

**Issue by hboomsma** [phpDocumentor/TypeResolver#19]
Today our PHP-nightly (currently 7.1) regression tests showed us that a class named Void was added to the TypeResolver. Void is a reserved keyword in the PHP 7.1 and having a class named voids triggers a fatal error.

Possible fix in #18.

**Comment by mvriel** [comment]
I have merged your contribution in #18; does this resolve this issue for you?

**Comment by hboomsma** [comment]
It does :+1:
