### ISSUE TITLE
PHP Parser v5 support

### ISSUE THREAD

**Issue by GrahamCampbell** [phpDocumentor/TypeResolver#204]
https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-5.0.md

**Comment by jaapio** [comment]
Not sure why this issue has been created. Are there any issues regarding php parser v5 and this library?

**Comment by GrahamCampbell** [comment]
This library requires php-parser v4, but some other libraries like phpunit 11 require v5, so it's not possible to co-install them.

**Comment by GrahamCampbell** [comment]
Ah, nvm, it's not this library. Sorry!

**Comment by jaapio** [comment]
That issue has been resolved, if I remember this correctly in phpunit 9?

**Comment by GrahamCampbell** [comment]
PHPUnit 11 released a few weeks ago now needs v5, but almost every other library that requires it, still requires v4.
