### ISSUE TITLE
PHP 7.1 compatibility - Implement Nullable types

### ISSUE THREAD

**Issue by asgrim** [phpDocumentor/TypeResolver#31]
I'd like to patch TypeResolver to handle nullable types. Would you prefer a `Nullable` type with actual type as child, or would you prefer a "flag" to be added to all the types? I think the former is cleaner (and echos how the AST is structured in PhpParser) but just wanted to check what your thoughts were before submitting a patch :) thanks!

**Comment by jaapio** [comment]
The type itself doesn't have to change for this. A Nullable type to wrap the actual type seems to be the right  way to implement this.

Looking forward to your patch :+1:

**Comment by asgrim** [comment]
Excellent thanks - will work on this shortly!
