### ISSUE TITLE
The default value for array keys could be more strict

### ISSUE THREAD

**Issue by stof** [phpDocumentor/TypeResolver#4]
Only integers and strings are valid array keys. So what about using ``int|string`` as default key type rather than ``mixed`` ?

**Comment by mvriel** [comment]
Sounds good; I wasn't sure whether boolean and float were rejected. Just checked using the interactive mode and they are indeed cast to integer

**Comment by mvriel** [comment]
And resolved on master, thanks

**Comment by stof** [comment]
You can write a boolean or a float as key in your source. But PHP will just cast them (as string or int, I don't remember) and use the casted value as key (same for ``null``).

**Comment by stof** [comment]
Your fix made some test become risky btw.

And note that you committed with an email address not associated with your github account.

**Comment by mvriel** [comment]
I will look into that tomorrow (time to catch some sleep); thanks for the heads up
