### ISSUE TITLE
Class with name "Scalar" is not resolved right

### ISSUE THREAD

**Issue by kukulich** [phpDocumentor/TypeResolver#43]
It's resolved as `phpDocumentor\Reflection\Type\Scalar` but it should be resolved as `phpDocumentor\Reflection\Type\Object_`.

**Comment by kukulich** [comment]
There would be problem with other names like `mixed`, `callback` etc. All names that are not reserved should be resolved case sensitive.

**Comment by GrahamCampbell** [comment]
I think this is actually a no-fix, since types in php are not case sensitive.

**Comment by jaapio** [comment]
This is related to #18.
According to the explanation of @mvriel this can not be achieved. This is more or less an php issue.

**Comment by jaapio** [comment]
Closing this will be tracked in #18
