### ISSUE TITLE
Document what TypeResolver does with nullable types

### ISSUE THREAD

**Issue by TysonAndre** [phpDocumentor/TypeResolver#45]
https://github.com/phpDocumentor/TypeResolver/pull/35/files implemented support for these, but does not mention "nullable" anywhere in the README.md of this project.

Questions I have:

- Could you update the README to mention where nullables are supported?
- Is phpdoc nullable supported? (No movement in http://www.php-fig.org/psr/ PSR-5 lately)
- If it is, add integration tests to make the supported locations clear? (e.g. parsing `/** @param ?int $x*/ function test($x);`)

**Comment by jaapio** [comment]
I added the missing chapter to the Readme. 

phpdoc will support nullable in the future. We started a new working group to continue the work on PSR-5.
This library only resolves the types. It doesn't parse docblocks. Have a look at https://github.com/phpDocumentor/ReflectionDocBlock to see how to parse docblocks.
