### ISSUE TITLE
[0.5.0] Array Syntax

### ISSUE THREAD

**Issue by GrahamCampbell** [phpDocumentor/TypeResolver#49]
The following is accepted by the parser: `array<string,float>`, but this is not: `array<string, float>`. Is that intentional?

```
RuntimeException: A type is missing in a collection expression

phpdocumentor/type-resolver/src/TypeResolver.php:240
phpdocumentor/type-resolver/src/TypeResolver.php:448
phpdocumentor/type-resolver/src/TypeResolver.php:204
phpdocumentor/type-resolver/src/TypeResolver.php:126
```

**Comment by jaapio** [comment]
I did't think about that case, I think it should be possible to add that to the tokenizer. But I think it MUST only contain 1 space, multiple should result in an error.

**Comment by GrahamCampbell** [comment]
Do you want to implement this, or shall I? I don't want us both to implement it at the same time you see. :)

**Comment by jaapio** [comment]
Pr is much appreciated. Didn't have time to get in to this

**Comment by ashnazg** [comment]
@jaapio so you're thinking the only allowed variation from `array<string,float>` is just the single space after the comma, `array<string, float>`... no other extra spacing is allowed... right?

**Comment by jaapio** [comment]
@ashnazg correct, it doesn't make sense.
