### ISSUE TITLE
php7 Compatibility problem

### ISSUE THREAD

**Issue by oasfuyou** [phpDocumentor/TypeResolver#66]
FILE: vendor/phpdocumentor/type-resolver/src/Types/Resource.php

 20 | WARNING | 'resource' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_CLASS)

vendor/phpdocumentor/type-resolver/src/Types/Mixed.php
 20 | WARNING | 'mixed' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_CLASS)

**Comment by jaapio** [comment]
This issue was resolved in a later release of type resolver. Please update
