### ISSUE TITLE
How can I return "true" && "false" as type?

### ISSUE THREAD

**Issue by voku** [phpDocumentor/TypeResolver#70]
I hacked a small patch into the "phpstorm-stubs" repo, so that we have the same types from code-analyse and in the IDE.

So I try to check return types from "psalm"... but I get "Boolean" type instead of some specific type, also if "false" is in the phpdoc? Can you please help me here, thanks!

https://github.com/JetBrains/phpstorm-stubs/pull/553/commits/c607771c9aacf9152d4c41aa425370a56ebe6d19#diff-2a66afccae99e70ecf1c63181957539aR138

**Comment by jaapio** [comment]
Hi @voku,

It is unclear to me what you get and expect. Could you please provide a table like. It sounds like we are doing something different that psalm does. maybe we can align this. 

| input | output | expected

**Comment by voku** [comment]
I  solved my problem with some new Type classes (Boolean False, Boolean True, ...) ... it works for my use-case, so I will close this issue.
