### ISSUE TITLE
fqsen and global variables

### ISSUE THREAD

**Issue by ancpru** [phpDocumentor/TypeResolver#71]
Hi,

Is 

`\My\Full\Namespace\$fooBar`

supposed to be valid for a global variable? The constructor of Fqsen tells me, that it's not. But how are global variables supposed to be referenced then?

**Update**: 

Beside the point of validity of the syntax, this problem arised in another way.

I created so many wrapping classes that I am not sure if I introduced a problem or if it's working as it is supposed to work:

I have a 
```
/*
* @see $variableInClass
*/
```

somewhere in the class docblocks. it's supposed to reference the member variable inside the class.

FqsenResolver/TypeResolver seems to turn this into  `\My\Current\Namespace\$variableInClass`. not `\My\Current\Namespace\CurrentClass::$variableInClass` as I would expect. The same seems to be the case for methods. 

Does Phpdocumentor now always need something like  static::$xyz, self::$xyz,  static::method(), self::method() in order to prevent this, or did I introduce a problem somewhere?

BTW, would'nt it be nice to have the current class available in Context - or is it unknown at the time of parsing docblocks?

**Comment by jaapio** [comment]
As far as I know variables cannot be namespaced in php. Variables are always defined in a global scope. It you want to have some kind of namespacing for variables you have to defined them in classes as property. which will give you the notation `\myClass::$var`, or a constant that is defined in a namespace `\myNamespace::VAR`
