### ISSUE TITLE
List can be created with null value but getter is typehinted to object

### ISSUE THREAD

**Issue by andrei-dascalu** [phpDocumentor/TypeResolver#78]
``CRITICAL  TypeError: Return value of phpDocumentor\Reflection\Types\AbstractList::getValueType() must implement interface phpDocumentor\Reflection\Type, null returned in <edited>/.vscode/extensions/felixfbecker.php-intellisense-2.3.13/vendor/phpdocumentor/type-resolver/src/Types/AbstractList.php:63``

Not entirely sure about the intended behaviour but if null is acceptable value then the getter should be allowed to return it as such, no?

**Comment by jaapio** [comment]
I'm wondering how you created this object, because the constructor of the class forces a value to be set when the provided value was `null` 
https://github.com/phpDocumentor/TypeResolver/blob/master/src/Types/AbstractList.php#L37

So some call to parent constructor is missing somewhere?

**Comment by jaapio** [comment]
I'm closing this issue due a leak of activity. If this issue still persists please respond to this issue and we will re-open it. 
However, I think we changed a lot in this package last year so I don't expect this to happen anymore.
