### ISSUE TITLE
Release version with iterable support

### ISSUE THREAD

**Issue by othercorey** [phpDocumentor/TypeResolver#91]
I don't know where else to ask this.

Could you tag a 1.0.2 release with the `iterable` type support?

**Comment by jaapio** [comment]
Hi @othercorey,

Correct me if I'm wrong but iteratable is already part of the last release... Is there something you are missing right now?

**Comment by othercorey** [comment]
https://github.com/phpDocumentor/TypeResolver/commit/b14efa60d44bdb7ee0318ccb551442779619e98b

This commit adds the `iterable` support and isn't in the current release.

**Comment by jaapio** [comment]
Released  now
