### ISSUE TITLE
1.1.0 release soon?

### ISSUE THREAD

**Issue by GrahamCampbell** [phpDocumentor/TypeResolver#92]
Will a 1.1.0 tag be coming soon. Is there anything you need a hand with?

**Comment by GrahamCampbell** [comment]
Relates to https://github.com/phpDocumentor/TypeResolver/issues/91. NB 1.1.0 drops PHP 7.1 support...

**Comment by GrahamCampbell** [comment]
I think we could easily add back PHP 7.1 support though?

**Comment by GrahamCampbell** [comment]
// cc @jaapio

**Comment by jaapio** [comment]
Released now.

I don't want to support php 7.1 anymore, it is end of life. there are no bugfixes in the new release that might have large impact on users. Most important reason to drop php 7.1 is that phpunit 8 is improved so we can finally have a working ci that doesn't break every once in a while. If you are still running php 7.1 please upgrade, or stay on v1.0 which will work for you in most cases.

**Comment by GrahamCampbell** [comment]
Should we bump to 7.2 on all the phpdocumentor packages that depend on type-resolver too then?

**Comment by jaapio** [comment]
Think they all are :-)

**Comment by GrahamCampbell** [comment]
Oh yes. 👍 for this then.
